# Generated by Django 2.2.15 on 2020-08-11 20:05

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=account.models.get_default_profile_image, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
