# Generated by Django 2.2.15 on 2020-08-13 21:03

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=50, null=True, storage=account.models.OverwriteStorage(), upload_to=account.models.get_profile_image_filepath),
        ),
    ]
