# Generated by Django 2.2.15 on 2020-09-15 18:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0005_auto_20200915_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], help_text='primary keys of users who are connected to chat room.', null=True, size=None, unique=True),
        ),
    ]
