# Generated by Django 2.2.15 on 2020-09-15 20:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0008_auto_20200915_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='primary keys of users who are connected to chat room.', size=None),
        ),
    ]
