# Generated by Django 2.2.15 on 2020-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0010_auto_20200921_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='guests',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
