# Generated by Django 2.2.15 on 2020-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_action_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_object',
            field=models.URLField(blank=True, help_text='The URL to be executed if clicked by the Target (User).', max_length=500, null=True),
        ),
    ]
