# Generated by Django 2.2.15 on 2020-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_action_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_object',
        ),
        migrations.AddField(
            model_name='notification',
            name='negative_action_object',
            field=models.URLField(blank=True, help_text='The URL to be executed if declined by the Target (User).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='positive_action_object',
            field=models.URLField(blank=True, help_text='The URL to be executed if accepted by the Target (User).', max_length=500, null=True),
        ),
    ]
