# Generated by Django 2.2.15 on 2020-08-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200825_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='completion_verb',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
