# Generated by Django 2.2.15 on 2020-08-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notification_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_active',
        ),
    ]
