# Generated by Django 2.2.15 on 2020-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_remove_notification_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
