# Generated by Django 2.2.15 on 2020-08-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20200825_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='completion_verb',
        ),
    ]
