# Generated by Django 2.2.15 on 2020-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_remove_notification_completion_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, help_text='Thumbnail image for notification', max_length=500, null=True),
        ),
    ]
