# Generated by Django 2.2.15 on 2020-08-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20200826_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
