# Generated by Django 2.2.15 on 2020-09-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='negative_action_object',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='positive_action_object',
        ),
    ]
