# Generated by Django 2.2.15 on 2020-08-18 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200817_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connected_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
