# Generated by Django 2.2.15 on 2020-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchatmessage',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
