# Generated by Django 2.2.15 on 2020-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_privatechatroom_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='reset_timestamp',
            field=models.DateTimeField(),
        ),
    ]
