# Generated by Django 2.2.15 on 2020-08-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200825_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadchatroommessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
