# Generated by Django 2.2.15 on 2020-08-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_unreadchatroommessages_most_recent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
