# Generated by Django 2.2.15 on 2020-08-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200825_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.PrivateChatRoom'),
        ),
    ]
