# Generated by Django 2.2.15 on 2020-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200826_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchatmessage',
            name='content',
            field=models.TextField(),
        ),
    ]
