# Generated by Django 2.2.15 on 2020-08-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20200819_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='message',
        ),
    ]
