# Generated by Django 2.2.15 on 2020-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_remove_friendrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
