
MSG_TYPE_NOTIFICATIONS_PAYLOAD = 0  # New notifications data payload incoming
MSG_TYPE_PAGINATION_EXHAUSTED = 1  # No more notifications to retrieve
MSG_TYPE_NOTIFICATIONS_REFRESH_PAYLOAD = 2  # Retrieved all notifications newer than the oldest visible on screen

MESSAGE_TYPES_CHOICES = (
    (MSG_TYPE_NOTIFICATIONS_PAYLOAD, 'NOTIFICATIONS_PAYLOAD'),
    (MSG_TYPE_PAGINATION_EXHAUSTED, 'PAGINATION_EXHAUSTED'),
    (MSG_TYPE_NOTIFICATIONS_REFRESH_PAYLOAD, 'NOTIFICATIONS_REFRESH_PAYLOAD'),
)

MESSAGE_TYPES_LIST = [
    MSG_TYPE_NOTIFICATIONS_PAYLOAD,
    MSG_TYPE_PAGINATION_EXHAUSTED,
    MSG_TYPE_NOTIFICATIONS_REFRESH_PAYLOAD,
]